Data Exploartion

In [ ]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("test.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [3]:
print(f"Number of Rows: {df.shape[0]}\nNumber of columns:{df.shape[1]}")

Number of Rows: 1459
Number of columns:80

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

Data perprocessing for  dataset

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     565 non-null    object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [7]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

In [8]:
print("---Attribute in Data---")
for cols in df.columns:
    print(cols)

---Attribute in Data---
Id
MSSubClass
MSZoning
LotFrontage
LotArea
Street
Alley
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
OverallQual
OverallCond
YearBuilt
YearRemodAdd
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
MasVnrType
MasVnrArea
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinSF1
BsmtFinType2
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
Heating
HeatingQC
CentralAir
Electrical
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
KitchenQual
TotRmsAbvGrd
Functional
Fireplaces
FireplaceQu
GarageType
GarageYrBlt
GarageFinish
GarageCars
GarageArea
GarageQual
GarageCond
PavedDrive
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
PoolQC
Fence
MiscFeature
MiscVal
MoSold
YrSold
SaleType
SaleCondition

In [9]:
print("---Number of instance in data---")
print(df.count())

---Number of instance in data---
Id               1459
MSSubClass       1459
MSZoning         1455
LotFrontage      1232
LotArea          1459
                 ...
MiscVal          1459
MoSold           1459
YrSold           1459
SaleType         1458
SaleCondition    1459
Length: 80, dtype: int64

In [10]:
print("-- nunique data--")
print(df.nunique())

-- nunique data--
Id               1459
MSSubClass         16
MSZoning            5
LotFrontage       115
LotArea          1106
                 ...
MiscVal            26
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
Length: 80, dtype: int64

In [11]:
print("-- Number of null value in data---")
df.isnull().sum()

-- Number of null value in data---

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [12]:
print("-- Number of Dublicate value in data---")
df.duplicated().sum()

-- Number of Dublicate value in data---

np.int64(0)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     565 non-null    object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [14]:
min_values = df.min(numeric_only=True)
print(min_values)

Id               1461.0
MSSubClass         20.0
LotFrontage        21.0
LotArea          1470.0
OverallQual         1.0
OverallCond         1.0
YearBuilt        1879.0
YearRemodAdd     1950.0
MasVnrArea          0.0
BsmtFinSF1          0.0
BsmtFinSF2          0.0
BsmtUnfSF           0.0
TotalBsmtSF         0.0
1stFlrSF          407.0
2ndFlrSF            0.0
LowQualFinSF        0.0
GrLivArea         407.0
BsmtFullBath        0.0
BsmtHalfBath        0.0
FullBath            0.0
HalfBath            0.0
BedroomAbvGr        0.0
KitchenAbvGr        0.0
TotRmsAbvGrd        3.0
Fireplaces          0.0
GarageYrBlt      1895.0
GarageCars          0.0
GarageArea          0.0
WoodDeckSF          0.0
OpenPorchSF         0.0
EnclosedPorch       0.0
3SsnPorch           0.0
ScreenPorch         0.0
PoolArea            0.0
MiscVal             0.0
MoSold              1.0
YrSold           2006.0
dtype: float64

In [15]:
max_values = df.min(numeric_only=True)
print(max_values)

Id               1461.0
MSSubClass         20.0
LotFrontage        21.0
LotArea          1470.0
OverallQual         1.0
OverallCond         1.0
YearBuilt        1879.0
YearRemodAdd     1950.0
MasVnrArea          0.0
BsmtFinSF1          0.0
BsmtFinSF2          0.0
BsmtUnfSF           0.0
TotalBsmtSF         0.0
1stFlrSF          407.0
2ndFlrSF            0.0
LowQualFinSF        0.0
GrLivArea         407.0
BsmtFullBath        0.0
BsmtHalfBath        0.0
FullBath            0.0
HalfBath            0.0
BedroomAbvGr        0.0
KitchenAbvGr        0.0
TotRmsAbvGrd        3.0
Fireplaces          0.0
GarageYrBlt      1895.0
GarageCars          0.0
GarageArea          0.0
WoodDeckSF          0.0
OpenPorchSF         0.0
EnclosedPorch       0.0
3SsnPorch           0.0
ScreenPorch         0.0
PoolArea            0.0
MiscVal             0.0
MoSold              1.0
YrSold           2006.0
dtype: float64

Now we work on outliear of the solution. We will use the following steps to solve the problem:
here we working on floating number

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     565 non-null    object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [17]:
q1_value = df.quantile(0.25, numeric_only=True)
print(q1_value)

Id               1825.50
MSSubClass         20.00
LotFrontage        58.00
LotArea          7391.00
OverallQual         5.00
OverallCond         5.00
YearBuilt        1953.00
YearRemodAdd     1963.00
MasVnrArea          0.00
BsmtFinSF1          0.00
BsmtFinSF2          0.00
BsmtUnfSF         219.25
TotalBsmtSF       784.00
1stFlrSF          873.50
2ndFlrSF            0.00
LowQualFinSF        0.00
GrLivArea        1117.50
BsmtFullBath        0.00
BsmtHalfBath        0.00
FullBath            1.00
HalfBath            0.00
BedroomAbvGr        2.00
KitchenAbvGr        1.00
TotRmsAbvGrd        5.00
Fireplaces          0.00
GarageYrBlt      1959.00
GarageCars          1.00
GarageArea        318.00
WoodDeckSF          0.00
OpenPorchSF         0.00
EnclosedPorch       0.00
3SsnPorch           0.00
ScreenPorch         0.00
PoolArea            0.00
MiscVal             0.00
MoSold              4.00
YrSold           2007.00
Name: 0.25, dtype: float64

In [18]:
q2_value = df.quantile(0.50, numeric_only=True)
print(q2_value)

Id               2190.0
MSSubClass         50.0
LotFrontage        67.0
LotArea          9399.0
OverallQual         6.0
OverallCond         5.0
YearBuilt        1973.0
YearRemodAdd     1992.0
MasVnrArea          0.0
BsmtFinSF1        350.5
BsmtFinSF2          0.0
BsmtUnfSF         460.0
TotalBsmtSF       988.0
1stFlrSF         1079.0
2ndFlrSF            0.0
LowQualFinSF        0.0
GrLivArea        1432.0
BsmtFullBath        0.0
BsmtHalfBath        0.0
FullBath            2.0
HalfBath            0.0
BedroomAbvGr        3.0
KitchenAbvGr        1.0
TotRmsAbvGrd        6.0
Fireplaces          0.0
GarageYrBlt      1979.0
GarageCars          2.0
GarageArea        480.0
WoodDeckSF          0.0
OpenPorchSF        28.0
EnclosedPorch       0.0
3SsnPorch           0.0
ScreenPorch         0.0
PoolArea            0.0
MiscVal             0.0
MoSold              6.0
YrSold           2008.0
Name: 0.5, dtype: float64

In [19]:
q3_value = df.quantile(0.75, numeric_only=True)
print(q3_value)

Id                2554.50
MSSubClass          70.00
LotFrontage         80.00
LotArea          11517.50
OverallQual          7.00
OverallCond          6.00
YearBuilt         2001.00
YearRemodAdd      2004.00
MasVnrArea         164.00
BsmtFinSF1         753.50
BsmtFinSF2           0.00
BsmtUnfSF          797.75
TotalBsmtSF       1305.00
1stFlrSF          1382.50
2ndFlrSF           676.00
LowQualFinSF         0.00
GrLivArea         1721.00
BsmtFullBath         1.00
BsmtHalfBath         0.00
FullBath             2.00
HalfBath             1.00
BedroomAbvGr         3.00
KitchenAbvGr         1.00
TotRmsAbvGrd         7.00
Fireplaces           1.00
GarageYrBlt       2002.00
GarageCars           2.00
GarageArea         576.00
WoodDeckSF         168.00
OpenPorchSF         72.00
EnclosedPorch        0.00
3SsnPorch            0.00
ScreenPorch          0.00
PoolArea             0.00
MiscVal              0.00
MoSold               8.00
YrSold            2009.00
Name: 0.75, dtype: float64

In [20]:
def remove_outliers(df, cols):
    for col in cols:
        q1 = df[col].quantile(0.25)  
        q3 = df[col].quantile(0.75)  
        iqr = q3 - q1  
        lower_bound = q1 - 1.5 * iqr  
        upper_bound = q3 + 1.5 * iqr  

        print(f'{col} -> Lower Bound: {lower_bound}, \nUpper Bound: {upper_bound}\n')
        
        
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    
    return df 


cols = df.select_dtypes(include=[np.number]).columns.tolist()  

df_cleaned = remove_outliers(df, cols)


print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

Id -> Lower Bound: 732.0,
Upper Bound: 3648.0

MSSubClass -> Lower Bound: -55.0,
Upper Bound: 145.0

LotFrontage -> Lower Bound: 30.0,
Upper Bound: 110.0

LotArea -> Lower Bound: 2146.125,
Upper Bound: 16423.125

OverallQual -> Lower Bound: 2.0,
Upper Bound: 10.0

OverallCond -> Lower Bound: 3.5,
Upper Bound: 7.5

YearBuilt -> Lower Bound: 1879.0,
Upper Bound: 2079.0

YearRemodAdd -> Lower Bound: 1895.0,
Upper Bound: 2071.0

MasVnrArea -> Lower Bound: -245.25,
Upper Bound: 408.75

BsmtFinSF1 -> Lower Bound: -1089.75,
Upper Bound: 1816.25

BsmtFinSF2 -> Lower Bound: 0.0,
Upper Bound: 0.0

BsmtUnfSF -> Lower Bound: -617.625,
Upper Bound: 1819.375

TotalBsmtSF -> Lower Bound: 82.25,
Upper Bound: 2024.25

1stFlrSF -> Lower Bound: 161.5,
Upper Bound: 2061.5

2ndFlrSF -> Lower Bound: -1006.5,
Upper Bound: 1677.5

LowQualFinSF -> Lower Bound: 0.0,
Upper Bound: 0.0

GrLivArea -> Lower Bound: 368.0,
Upper Bound: 2432.0

BsmtFullBath -> Lower Bound: -1.5,
Upper Bound: 2.5

BsmtHalfBath -> Lower Bound: 0.0,
Upper Bound: 0.0

FullBath -> Lower Bound: -0.5,
Upper Bound: 3.5

HalfBath -> Lower Bound: -1.5,
Upper Bound: 2.5

BedroomAbvGr -> Lower Bound: 0.5,
Upper Bound: 4.5

KitchenAbvGr -> Lower Bound: 1.0,
Upper Bound: 1.0

TotRmsAbvGrd -> Lower Bound: 2.0,
Upper Bound: 10.0

Fireplaces -> Lower Bound: -1.5,
Upper Bound: 2.5

GarageYrBlt -> Lower Bound: 1890.0,
Upper Bound: 2074.0

GarageCars -> Lower Bound: -0.5,
Upper Bound: 3.5

GarageArea -> Lower Bound: 20.5,
Upper Bound: 912.5

WoodDeckSF -> Lower Bound: -251.625,
Upper Bound: 419.375

OpenPorchSF -> Lower Bound: -105.0,
Upper Bound: 175.0

EnclosedPorch -> Lower Bound: 0.0,
Upper Bound: 0.0

3SsnPorch -> Lower Bound: 0.0,
Upper Bound: 0.0

ScreenPorch -> Lower Bound: 0.0,
Upper Bound: 0.0

PoolArea -> Lower Bound: 0.0,
Upper Bound: 0.0

MiscVal -> Lower Bound: 0.0,
Upper Bound: 0.0

MoSold -> Lower Bound: -2.0,
Upper Bound: 14.0

YrSold -> Lower Bound: 2004.0,
Upper Bound: 2012.0

Original DataFrame shape: (1459, 80)
Cleaned DataFrame shape: (430, 80)

In [21]:
df.fillna(df.mean(numeric_only=True), inplace=True) 
df.fillna(df.mode().iloc[0], inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   object
 3   LotFrontage    1459 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          1459 non-null   object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1459 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1459 non-null   object
 24  Exterior2nd    1459 non-null   object
 25  MasVnrType     1459 non-null   object
 26  MasVnrArea     1459 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1459 non-null   object
 31  BsmtCond       1459 non-null   object
 32  BsmtExposure   1459 non-null   object
 33  BsmtFinType1   1459 non-null   object
 34  BsmtFinSF1     1459 non-null   float64
 35  BsmtFinType2   1459 non-null   object
 36  BsmtFinSF2     1459 non-null   float64
 37  BsmtUnfSF      1459 non-null   float64
 38  TotalBsmtSF    1459 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1459 non-null   float64
 48  BsmtHalfBath   1459 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1459 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1459 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    1459 non-null   object
 58  GarageType     1459 non-null   object
 59  GarageYrBlt    1459 non-null   float64
 60  GarageFinish   1459 non-null   object
 61  GarageCars     1459 non-null   float64
 62  GarageArea     1459 non-null   float64
 63  GarageQual     1459 non-null   object
 64  GarageCond     1459 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         1459 non-null   object
 73  Fence          1459 non-null   object
 74  MiscFeature    1459 non-null   object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1459 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [23]:
def convertFloatintoInt(cols):
    for col in cols:
        df[col] = df[col].astype('int64') 
columns = df.select_dtypes(include=['float']).columns  
convertFloatintoInt(columns)

In [24]:
def dataEncoder(cols):
    for i in cols:
        dataLabelEncoder = LabelEncoder()
        df[i] = dataLabelEncoder.fit_transform(df[i])
columns = [catgory for catgory in df.columns if df[catgory].dtype == 'object']
dataEncoder(columns)

In [25]:
for col in df.select_dtypes(include=['int32', 'int64']).columns:
    df[col] = df[col].astype('int64')

df.to_csv("train_int64.csv", index=False)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1459 non-null   int64
 3   LotFrontage    1459 non-null   int64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   int64
 6   Alley          1459 non-null   int64
 7   LotShape       1459 non-null   int64
 8   LandContour    1459 non-null   int64
 9   Utilities      1459 non-null   int64
 10  LotConfig      1459 non-null   int64
 11  LandSlope      1459 non-null   int64
 12  Neighborhood   1459 non-null   int64
 13  Condition1     1459 non-null   int64
 14  Condition2     1459 non-null   int64
 15  BldgType       1459 non-null   int64
 16  HouseStyle     1459 non-null   int64
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   int64
 22  RoofMatl       1459 non-null   int64
 23  Exterior1st    1459 non-null   int64
 24  Exterior2nd    1459 non-null   int64
 25  MasVnrType     1459 non-null   int64
 26  MasVnrArea     1459 non-null   int64
 27  ExterQual      1459 non-null   int64
 28  ExterCond      1459 non-null   int64
 29  Foundation     1459 non-null   int64
 30  BsmtQual       1459 non-null   int64
 31  BsmtCond       1459 non-null   int64
 32  BsmtExposure   1459 non-null   int64
 33  BsmtFinType1   1459 non-null   int64
 34  BsmtFinSF1     1459 non-null   int64
 35  BsmtFinType2   1459 non-null   int64
 36  BsmtFinSF2     1459 non-null   int64
 37  BsmtUnfSF      1459 non-null   int64
 38  TotalBsmtSF    1459 non-null   int64
 39  Heating        1459 non-null   int64
 40  HeatingQC      1459 non-null   int64
 41  CentralAir     1459 non-null   int64
 42  Electrical     1459 non-null   int64
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1459 non-null   int64
 48  BsmtHalfBath   1459 non-null   int64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1459 non-null   int64
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1459 non-null   int64
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    1459 non-null   int64
 58  GarageType     1459 non-null   int64
 59  GarageYrBlt    1459 non-null   int64
 60  GarageFinish   1459 non-null   int64
 61  GarageCars     1459 non-null   int64
 62  GarageArea     1459 non-null   int64
 63  GarageQual     1459 non-null   int64
 64  GarageCond     1459 non-null   int64
 65  PavedDrive     1459 non-null   int64
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         1459 non-null   int64
 73  Fence          1459 non-null   int64
 74  MiscFeature    1459 non-null   int64
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1459 non-null   int64
 79  SaleCondition  1459 non-null   int64
dtypes: int64(80)
memory usage: 912.0 KB

In [27]:
df.to_csv("Updated_Test.csv", index=False)